spring:
  client:
    serviceUrl:
      defaultZone: http://localhost:9998/eureka/
    cloud:
        gateway:
            routes:
                - id: microservice-projet
                  uri: lb://MSProject
                  predicates:
                  - Path: /projet/**
                  filters:
                  - RewritePath= /projet/(?<path>.*) , /$\{path}

                - id: microservice-user
                  uri: lb://UserProject
                  predicates:
                  - Path: /user/**
                  filters:
                  - RewritePath= /utilisateur/(?<path>.*) , /$\{path}
